name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
                ssh-key: ${{ secrets.DEPLOY_KEY_PRIVATE }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
                ssh-private-key: ${{ secrets.DEPLOY_KEY_PRIVATE }}

      - name: Add known hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $VM_HOST >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST << 'EOF'
            cd /home/azureuser/simple-api
            git pull origin master
            npm install
            sudo npx pm2 stop simple-api || true
            sudo npx pm2 start app.js --name simple-api --watch           
          EOF
          
